import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.grid}>
          <Link href="/lista-viajes" className={styles.card}>
            <h2>
              Ejercicio 01 <span>-&gt;</span>
            </h2>
            <p>Solución del ejercicio 01.</p>
          </Link>

          <Link href="/reporte-tonelaje" className={styles.card}>
            <h2>
              Ejercicio 02 <span>-&gt;</span>
            </h2>
            <p>Solución del ejercicio 02.</p>
          </Link>
        </div>
      </main>
    </>
  );
}
